apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wayz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wayz
    app.kubernetes.io/part-of: tkwch-fix-0075-0023-app
  name: devfile-sample-wayz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wayz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wayz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0023-tenant/tkwch-fix-0075-0023-app/devfile-sample-wayz@sha256:601663886fbce0ecb2aca2eebe83bd910ed09263679071f574a4991fa3a0f352
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
